In [1]:
!python --version

Python 3.6.15


In [41]:
# Required Libraries
import numpy  as np
import math
import random
import os
import matplotlib.pyplot as plt

#Generating Initial Population S with Dimension d and Iterations N
S = 5
d = 2
N = 1

# Initialize Population of Wolves
X=[]
rows, cols= S, d
for i in range(rows):
    col = []
    for j in range(cols):
        col.append(round((random.uniform(-5,5)),4))
    X.append(col)

X = np.array(X)
X = X.reshape(S,d)
print("Randomly Generated Initial Population, X\n", X)

# Starting With Iterations
for n in range(N):
    print("\nIteration No :", n)
    X_upt = []
    for s in range(S):
        print("\nWolf No :", s)
        X_init = X[s]      # Initial Position of Prey
        #X_upt = []         # Updated Wolves Position Vector 
        # Generating random values A
        a = 2 - i/N
        A=[]
        rows, cols = S, d
        for j in range(rows):
            for k in range(cols):
                r = random.random()
                A.append(round((2*a*r - a),2))
            A.append
        A = np.array(A)
        A = A.reshape(S,d)
        print("Randomly Generated Values of A\n", A)

        # Generating random values C
        C=[]
        rows, cols = S, d
        for i in range(rows):
            for j in range(cols):
                C.append(round((2*random.random()),2))
        C = np.array(C)
        C = C.reshape(S,d)
        print("Randomly Generated Values of C\n", C)

        # Calculating Fitness Function F1
        F1=[]
        rows = S
        for i in range(rows):
            F1.append(round((X[i][0]**2 + X[i][1]**2),4))
            F1.append
        print("\nCorresponding Fitness Values = ", F1)

        F1.sort()
        print("\nSorted Fitness Values\n", F1)

        Fα = F1[0]; print("\nFα", Fα)
        Fβ = F1[1]; print("Fβ", Fβ)
        Fδ = F1[2]; print("Fδ", Fδ)

        for i in range(rows):
            sol = round((X[i][0]**2 + X[i][1]**2),4)
            if(sol == Fα):
                Xα = X[i]; print("Xα", Xα)
            if(sol == Fβ):
                Xβ = X[i]; print("Xβ", Xβ)
            if(sol == Fδ):
                Xδ = X[i]; print("Xδ", Xδ)
            F1.append  
    
        # Calculating D Values
        Da = []; Db = []; Dc = [];
            
        for j in range(d):
            Da.append(round(abs(C[0][j]*Xα[j] - X_init[j]),4)); #print("Da[0] = ", Da)
            Db.append(round(abs(C[1][j]*Xα[j] - X_init[j]),4)); #print("Db[0] = ", Db)
            Dc.append(round(abs(C[2][j]*Xα[j] - X_init[j]),4)); #print("Dc[0] = ", Dc)
            
        print("Dα ", Da)
        print("Dβ ", Db)
        print("Dδ ", Dc)
            
        # Calculating X1, X2 and X3 Values
        X1 = []; X2 = []; X3 = [];
            
        for j in range(d):
            X1.append(round(Xα[j]-A[0][j]* Da[j],4)); #print("X1 = ", X1[j])
            X2.append(round(Xβ[j]-A[1][j]* Da[j],4)); #print("X2 = ", X2[j])
            X3.append(round(Xδ[j]-A[2][j]* Dc[j],4)); #print("X3 = ", X3[j])
            
        print("X1 ", X1)
        print("X2 ", X2)
        print("X3 ", X3)
        
        X1 = np.array(X1)
        X2 = np.array(X2)
        X3 = np.array(X3)
            
        X_upt.append((X1 + X2 + X3)/3); print("\nX_upt", X_upt)
           
    s+=1
    
n+=1
 

Randomly Generated Initial Population, X
 [[-3.0181 -1.5964]
 [-0.1762  3.4171]
 [ 3.1543  4.4713]
 [ 1.2829  4.9679]
 [-2.4947  0.1862]]

Iteration No : 0

Wolf No : 0
Randomly Generated Values of A
 [[-0.37  0.94]
 [ 1.58 -1.34]
 [ 0.75 -1.15]
 [-0.89 -1.82]
 [-1.41  0.4 ]]
Randomly Generated Values of C
 [[1.34 1.83]
 [1.56 0.12]
 [1.48 1.88]
 [0.11 0.17]
 [1.8  1.12]]

Corresponding Fitness Values =  [11.6574, 11.7076, 29.9421, 26.3259, 6.2582]

Sorted Fitness Values
 [6.2582, 11.6574, 11.7076, 26.3259, 29.9421]

Fα 6.2582
Fβ 11.6574
Fδ 11.7076
Xβ [-3.0181 -1.5964]
Xδ [-0.1762  3.4171]
Xα [-2.4947  0.1862]
Dα  [0.3248, 1.9371]
Dβ  [0.8736, 1.6187]
Dδ  [0.6741, 1.9465]
X1  [-2.3745, -1.6347]
X2  [-3.5313, 0.9993]
X3  [-0.6818, 5.6556]

X_upt [array([-2.19586667,  1.6734    ])]

Wolf No : 1
Randomly Generated Values of A
 [[-0.85  0.01]
 [ 0.79  0.2 ]
 [-0.18  1.05]
 [-1.57  1.7 ]
 [ 1.24 -0.52]]
Randomly Generated Values of C
 [[1.06 0.62]
 [1.02 1.7 ]
 [0.41 0.21]
 [1.28 1.9 ]
 [1.

In [4]:
# Calculating D Values: Iteration 2

X = X_upt1

Xα =1; Xβ=2; Xδ=3
# generating random values A
A=[]
rows = 3
for i in range(rows):
    A.append(random.randint(-5,5))
print("Randomly Generated Values of A = ", A)

# generating random values C
C=[]
rows = 3
for i in range(rows):
    C.append(random.randint(-5,5))
print("Randomly Generated Values of C = ", C)


Dα = abs(C[0]*Xα - X); print("Dα", Dα)
Dβ = abs(C[1]*Xβ - X); print("Dβ", Dβ) 
Dδ = abs(C[2]*Xδ - X); print("Dδ", Dδ) 

X1  = Xα - A[0]* Dα; print("X1", X1)
X2  = Xβ - A[1]* Dβ; print("X2", X2)
X3  = Xδ - A[2]* Dδ; print("X3", X3)

X_upt2 = (X1 + X2 + X3 ) / 3; print("X_upt2", X_upt2)

Randomly Generated Values of A =  [3, 4, -3]
Randomly Generated Values of C =  [3, 5, 5]
Dα 1.0
Dβ 8.0
Dδ 13.0
X1 -2.0
X2 -30.0
X3 42.0
X_upt2 3.3333333333333335


In [5]:
# Calculating D Values : Iteration 3

X = X_upt2

Xα =1; Xβ=2; Xδ=3
# generating random values A
A=[]
rows = 3
for i in range(rows):
    A.append(random.randint(-5,5))
print("Randomly Generated Values of A = ", A)

# generating random values C
C=[]
rows = 3
for i in range(rows):
    C.append(random.randint(-5,5))
print("Randomly Generated Values of C = ", C)


Dα = abs(C[0]*Xα - X); print("Dα", Dα)
Dβ = abs(C[1]*Xβ - X); print("Dβ", Dβ) 
Dδ = abs(C[2]*Xδ - X); print("Dδ", Dδ) 

X1  = Xα - A[0]* Dα; print("X1", X1)
X2  = Xβ - A[1]* Dβ; print("X2", X2)
X3  = Xδ - A[2]* Dδ; print("X3", X3)

X_upt3 = (X1 + X2 + X3 ) / 3; print("X_upt3", X_upt3)

Randomly Generated Values of A =  [2, -4, -4]
Randomly Generated Values of C =  [2, 1, 1]
Dα 1.3333333333333335
Dβ 1.3333333333333335
Dδ 0.3333333333333335
X1 -1.666666666666667
X2 7.333333333333334
X3 4.333333333333334
X_upt3 3.3333333333333335


In [6]:
# Calculating D Values : Iteration 4

X = X_upt3

Xα =1; Xβ=2; Xδ=3
# generating random values A
A=[]
rows = 3
for i in range(rows):
    A.append(random.randint(-5,5))
print("Randomly Generated Values of A = ", A)

# generating random values C
C=[]
rows = 3
for i in range(rows):
    C.append(random.randint(-5,5))
print("Randomly Generated Values of C = ", C)


Dα = abs(C[0]*Xα - X); print("Dα", Dα)
Dβ = abs(C[1]*Xβ - X); print("Dβ", Dβ) 
Dδ = abs(C[2]*Xδ - X); print("Dδ", Dδ) 

X1  = Xα - A[0]* Dα; print("X1", X1)
X2  = Xβ - A[1]* Dβ; print("X2", X2)
X3  = Xδ - A[2]* Dδ; print("X3", X3)

X_upt4 = (X1 + X2 + X3 ) / 3; print("X_upt4", X_upt4)

Randomly Generated Values of A =  [2, 3, 4]
Randomly Generated Values of C =  [-1, 5, -2]
Dα 4.333333333333334
Dβ 6.666666666666666
Dδ 9.333333333333334
X1 -7.666666666666668
X2 -18.0
X3 -34.333333333333336
X_upt4 -20.0


In [7]:
# Calculating D Values : Iteration 5

X = X_upt4

Xα =1; Xβ=2; Xδ=3
# generating random values A
A=[]
rows = 3
for i in range(rows):
    A.append(random.randint(-5,5))
print("Randomly Generated Values of A = ", A)

# generating random values C
C=[]
rows = 3
for i in range(rows):
    C.append(random.randint(-5,5))
print("Randomly Generated Values of C = ", C)


Dα = abs(C[0]*Xα - X); print("Dα", Dα)
Dβ = abs(C[1]*Xβ - X); print("Dβ", Dβ) 
Dδ = abs(C[2]*Xδ - X); print("Dδ", Dδ) 

X1  = Xα - A[0]* Dα; print("X1", X1)
X2  = Xβ - A[1]* Dβ; print("X2", X2)
X3  = Xδ - A[2]* Dδ; print("X3", X3)

X_upt5 = (X1 + X2 + X3 ) / 3; print("X_upt5", X_upt5)

Randomly Generated Values of A =  [3, -5, 5]
Randomly Generated Values of C =  [-4, 2, -1]
Dα 16.0
Dβ 24.0
Dδ 17.0
X1 -47.0
X2 122.0
X3 -82.0
X_upt5 -2.3333333333333335
